/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pc.gltf
Author: Yolala1232 (https://sketchfab.com/Yolala1232)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-desktop-pc-d1d8282c9916438091f11aeb28787b66
Title: Gaming Desktop PC
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const {isMobile}=props
  const computer = useGLTF("/pc.gltf");
  return (
    <mesh>
      <hemisphereLight intensity={0.15} groundColor="black" />
      <pointLight intensity={1} />
      <spotLight 
      position={[-20,50,10]}
      angle={0.12}
      penumbra={1}
      intensity={1}
      castShadow 
      shadow-mapSize={1024}
      />
      <primitive object={computer.scene} position={isMobile?[0,-3,-2.2]: [0, -2.25, -.5]}
      rotation={[-0.01,-0.2,-0.1]} scale={isMobile? 0.7:0.90}
      />
    </mesh>
  );
}

useGLTF.preload("/pc.gltf");
